### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by djmaze** [TypeCellOS/TypeCell#336]
It seems the sub-packages are not organized correctly (?). At least not with the commands given in `CONTRIBUTING.md`.

```
# Install all required npm modules for lerna, and bootstrap lerna packages
npm install

# Initial build of all packages required by the main editor project
npm run build

# Start the main editor project
npm start
```

I needed to go to `packages/editors` and run `npm install --force` manually. But afterwards, the build still fails:

```
src/app/main/components/permissions/PermissionsLoader.tsx(71,16): error TS2322: Type '{ children: Element[]; css: { overflow: string; }; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & ModalDialogProps'.
  Property 'css' does not exist on type 'IntrinsicAttributes & ModalDialogProps'.
```

Is this still broken WIP code?

**Comment by YousefED** [comment]
This should now be fixed! (big refactor has since been shipped)

**Comment by djmaze** [comment]
Yeah! It works. 

```bash
npm install
npm run build
npm start
```

Now trying to setup the backend server as well.

Thanks for your work! :raised_hands:
